
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";
export const SET_PRODUCTS_FAILED = "SET_PRODUCTS_FAILED";
export const SET_PRODUCTS_REQUEST = "SET_PRODUCTS_REQUEST";
export const SET_PRODUCTS_SUCCESS = "SET_PRODUCTS_SUCCESS";
export const FILTER_PRODUCT = "FILTER_PRODUCT";