
export const SET_BLOGS_SUCCESS = "SET_BLOGS_SUCCESS";
export const SET_BLOG_REQUEST = "SET_BLOG_REQUEST";
export const SET_BLOG_FAILED = "SET_BLOG_FAILED";
export const SELECTED_BLOG = "SELECTED_BLOG";
export const REMOVE_SELECTED_BLOG = "REMOVE_SELECTED_BLOG";